"""empty message

Revision ID: 05a55165ebdd
Revises: fd4ede70ffa4
Create Date: 2019-08-31 22:09:30.165086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a55165ebdd'
down_revision = 'fd4ede70ffa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('discord_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'discord_name')
    # ### end Alembic commands ###
