"""empty message

Revision ID: 11edf236626f
Revises: 818d8ebcdf3f
Create Date: 2019-11-03 01:51:05.761468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11edf236626f'
down_revision = '818d8ebcdf3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
