"""empty message

Revision ID: 1e4af10787c5
Revises: cefb50c219c5
Create Date: 2019-04-18 15:59:43.901766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4af10787c5'
down_revision = 'cefb50c219c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'role')
    # ### end Alembic commands ###
