"""empty message

Revision ID: 2ada3c1d96c9
Revises: 5724929854e4
Create Date: 2019-11-02 19:09:28.091157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ada3c1d96c9'
down_revision = '5724929854e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'ingame_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['ingame_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'ingame_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
