"""empty message

Revision ID: 4530390a385e
Revises: 533f6151adf5
Create Date: 2019-12-08 19:11:47.701781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4530390a385e'
down_revision = '533f6151adf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amigosecretostate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('premio_minimo', sa.BigInteger(), nullable=True),
    sa.Column('premio_maximo', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amigosecretostate')
    # ### end Alembic commands ###
