"""empty message

Revision ID: 533f6151adf5
Revises: b0e7b0eea412
Create Date: 2019-12-07 23:55:58.537375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533f6151adf5'
down_revision = 'b0e7b0eea412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amigosecretostate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amigosecretostate')
    # ### end Alembic commands ###
