"""Update team player and advlogstate

Revision ID: 654c234cca11
Revises: 
Create Date: 2019-04-03 21:26:17.343200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654c234cca11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'botmessage', 'team', ['team'], ['id'], ondelete='CASCADE')
    op.add_column('player', sa.Column('secondary', sa.Boolean(), nullable=True))
    op.add_column('team', sa.Column('secondary_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'secondary_limit')
    op.drop_column('player', 'secondary')
    op.drop_constraint(None, 'botmessage', type_='foreignkey')
    # ### end Alembic commands ###
