"""empty message

Revision ID: 818d8ebcdf3f
Revises: 2ada3c1d96c9
Create Date: 2019-11-03 01:49:39.679850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818d8ebcdf3f'
down_revision = '2ada3c1d96c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
