"""

Revision ID: b02cedca3b67
Revises: 654c234cca11
Create Date: 2019-04-03 21:33:50.851501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02cedca3b67'
down_revision = '654c234cca11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
