"""empty message

Revision ID: b0e7b0eea412
Revises: 123fadbf95c1
Create Date: 2019-12-07 23:54:26.831088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e7b0eea412'
down_revision = '123fadbf95c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
