"""empty message

Revision ID: d90f554d7359
Revises: 11edf236626f
Create Date: 2019-12-07 03:05:45.083735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90f554d7359'
down_revision = '11edf236626f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amigosecreto', sa.Column('giving_to_user', sa.Integer(), nullable=True))
    op.add_column('amigosecreto', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('amigosecreto_discord_id_key', 'amigosecreto', type_='unique')
    op.drop_constraint('amigosecreto_giving_to_id_key', 'amigosecreto', type_='unique')
    op.drop_constraint('amigosecreto_giving_to_name_key', 'amigosecreto', type_='unique')
    op.create_unique_constraint(None, 'amigosecreto', ['user_id'])
    op.create_unique_constraint(None, 'amigosecreto', ['giving_to_user'])
    op.create_foreign_key(None, 'amigosecreto', 'user', ['giving_to_user'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'amigosecreto', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('amigosecreto', 'giving_to_id')
    op.drop_column('amigosecreto', 'discord_name')
    op.drop_column('amigosecreto', 'discord_id')
    op.drop_column('amigosecreto', 'giving_to_name')
    op.drop_column('amigosecreto', 'ingame_name')
    op.add_column('amigosecretostate', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('amigosecretostate', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amigosecretostate', 'start_date')
    op.drop_column('amigosecretostate', 'end_date')
    op.add_column('amigosecreto', sa.Column('ingame_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('amigosecreto', sa.Column('giving_to_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('amigosecreto', sa.Column('discord_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('amigosecreto', sa.Column('discord_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('amigosecreto', sa.Column('giving_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'amigosecreto', type_='foreignkey')
    op.drop_constraint(None, 'amigosecreto', type_='foreignkey')
    op.drop_constraint(None, 'amigosecreto', type_='unique')
    op.drop_constraint(None, 'amigosecreto', type_='unique')
    op.create_unique_constraint('amigosecreto_giving_to_name_key', 'amigosecreto', ['giving_to_name'])
    op.create_unique_constraint('amigosecreto_giving_to_id_key', 'amigosecreto', ['giving_to_id'])
    op.create_unique_constraint('amigosecreto_discord_id_key', 'amigosecreto', ['discord_id'])
    op.drop_column('amigosecreto', 'user_id')
    op.drop_column('amigosecreto', 'giving_to_user')
    # ### end Alembic commands ###
