"""empty message

Revision ID: fd4ede70ffa4
Revises: 8ed9599d1b2c
Create Date: 2019-08-30 21:37:46.610249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4ede70ffa4'
down_revision = '8ed9599d1b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
